name: DeliveryJob

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./test-app
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Chechkout 
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install, Test and Build
        run: |
          npm ci
          npm run test
          npm run build

      - name: package.json info
        id: info
        uses: jaywcjlove/github-action-package@main
        with:
          path: ./test-app/package.json
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: tovven/test-service
          tags: |
            type=raw,value=${{ steps.info.outputs.version }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./test-app
          push: true
          tags: ${{ steps.meta.outputs.tags }}
      
      - name: 'Kustomize Build'
        uses: karancode/kustomize-github-action@master
        with:
          kustomize_install: true
          kustomize_version: '5.0.0'
          kustomize_build_dir: 'test-app/kustomize/base'
          kustomize_output_file: "./deployment.yaml"
          kustomize_comment: false
      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}
      - run: kubectl apply -n test-namespace -f ./deployment.yaml
